name: Project CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Use NodeJS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci

      - name: Linting
        run: npm ci:lint

      - name: Typeckeck
        run: npm typecheck

      - name: Tests
        run: npm ci:test
